version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./docker/initdb/:/docker-entrypoint-initdb.d/
      - ./docker/data/mariadb/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  backend:
    container_name: blog-backend
    image: yellowsunn/blog-backend
    restart: always
    depends_on:
      - db
    volumes:
    - ./docker/data/upload/image:/upload/image

  frontend:
    container_name: blog-frontend
    image: yellowsunn/blog-front
    restart: always
    environment:
      VUE_APP_API_DOMAIN: 'http://yellowsunn.com:3000'

  proxy:
    container_name: blog-server
    image: nginx:1.21-alpine
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
