version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
#      - ./mariadb/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
    - "3307:3306"

#  backend:
#    container_name: backend
#    image: yellowsunn/blog-backend
#    restart: always
#    depends_on:
#      - db
#    volumes:
#    - ./upload/image:/upload/image
#    ports:
#      - "8080:8080"
#
#  frontend:
#    container_name: frontend
#    image: yellowsunn/blog-front
#    restart: always
#    environment:
#      VUE_APP_API_DOMAIN: localhost:8080
#    ports:
#      - "3000:80"
#      - "443:443"