spring:
  datasource:
    url: jdbc:mariadb://db:3306/blog_db?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: select 1
      leak-detection-threshold: 2000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  # 파일 업로드 용량
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

#logging.level:
#  org.hibernate:
#    SQL: debug
#    type: trace
#  com.zaxxer.hikari: TRACE

# 이미지 경로
file.upload.directory: ./upload/image/
imagePath: /image/

logging.level.root: warn